config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
   resources :pins do
    member do
      put "like", to: "pins#upvote"
      put "dislike", to: "pins#downvote"
    end
  end

  root "pins#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user
	acts_as_votable
	has_attached_file :image, styles: {medium: "300x300>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pins
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]


	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def show	
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to root_path, notice: "Successfully created a new pin"
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @pin.update(pin_params)
			redirect_to root_path, notice: "Pin was Successfully Updated"
		else
			render 'edit'
		end	
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.upvote_by current_user
		redirect_back(fallback_location: root_path)
	end

	def downvote
		@pin.downvote_by current_user
		redirect_back(fallback_location: root_path)
	end

	private
	
	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Pintrest
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_pack_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  
  %nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .container
      =link_to "Pinterest", root_path, class: "navbar-brand"
      %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNavDropdown", "data-bs-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarNavDropdown.collapse.navbar-collapse.justify-content-end
        %ul.navbar-nav
          - if user_signed_in?
            %li.nav-item
              = link_to "New Pin", new_pin_path, class: "nav-link active"
            %li.nav-item
              = link_to "Account", edit_user_registration_path, class: "nav-link"
            %li.nav-item
              = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"
          - else
            %li.nav-item
              = link_to "Sign Up", new_user_registration_path, class: "nav-link active"
            %li.nav-item
              = link_to "Sign In", new_user_session_path, class: "nav-link"
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true }, remote: true do |f|
	- if @pin.errors.any?
		#errors
			%h2
				= pluralize(@pin.errors.count, "error")
				prevented this Pin from saving
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :image, input_html: { class: 'form-control' }

	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }

	= f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
%div{ :class => "col-3 mt-5 m-auto" }
	%h1 Edit form 
	= image_tag @pin.image.url(:medium)
	= render 'form'

	= link_to "Cancle", pin_path

app/views/pins/index.html.haml
#pins.tranision-enabled

	%div.col-12.mt-5.m-auto.grid{"data-masonry" => "{ \"itemSelector\": \".grid-item\", \"columnWidth\": 0 }"}
	
		- @pins.each do |pin|
			.box.panel.panel-default.grid-item
				= link_to (image_tag pin.image.url), pin
				.panel-body
					%h2= link_to pin.title, pin
					%p.user
					Submitted by 
					=pin.user.email

app/views/pins/new.html.haml
%div{ :class => "col-3 mt-5 m-auto" }
	%h1 new form 

	= render 'form'

	= link_to "Back", root_path

app/views/pins/show.html.haml
#pin_show.row
	.col-md-6.col-md-offset-2.card.m-auto.mt-5
		.card-body
			.panel-heading.pin_image
				= image_tag @pin.image.url
				%h1.card-title.mt-4= @pin.title
				%p.card-text= @pin.description
			.card-footer.mt-4
				.d-flex.justify-content-between.align-items-center
					%p.user.m-0
						Submitted by
						= @pin.user.email

					.btn-group{"aria-label" => "Basic outlined example", :role => "group", id: "#{@pin.id}"}
						- if current_user.liked? @pin
							%span{ class: "dislike_as btn btn-outline-secondary" }
								%i.bi.bi-heart-fill
								= @pin.get_upvotes.size
						- else
							%span{ class: "like_as btn btn-outline-secondary" }
								%i.bi.bi-heart
								= @pin.get_upvotes.size
						- if current_user.id == @pin.user_id
							= link_to "Edit", edit_pin_path, class: "btn btn-outline-secondary"
							= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-secondary"



							